# Generated by Django 4.2.11 on 2025-06-15 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_projectopportunity_project_notification_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectopportunity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectopportunity',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='project_opportunities', to=settings.AUTH_USER_MODEL),
        ),
    ]
